<a href="https://colab.research.google.com/github/Andrehlb/DataScience_Embraer/blob/main/Aula_2_2_Criacao_de__arrays_pratica_Andrehlb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1> Numpy </h1>



In [1]:
#importando as bibliotecas
import numpy as np

In [ ]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array

In [ ]:
np.array?

In [ ]:
#criação de array 1D: [1,2,3]
l = [1,2,3]
x = np.array(l)
print('x = ', x)
print('o shape é:', x.shape)

x =  [1 2 3]
o shape é: (3,)


In [ ]:
type(x)

numpy.ndarray

In [ ]:
#criação de array 1D: [1,2,3]
#l = [1,2,3]
x = np.array([1,2,3])
print('x = ', x)
print('o shape é:', x.shape)

x =  [1 2 3]
o shape é: (3,)


In [ ]:
#criação de array 1D: [1,2,3] e forçando ser do tipo int
l = [1,2,3]
x = np.array(l, dtype=int)
print('x = ', x)
print('o shape é:', x.shape)

x =  [1 2 3]
o shape é: (3,)


In [ ]:
#criação de array 2D: [1,2], [3,4]
l = ([1,2], [3,4])
x = np.array(l)
print('x:\n', x)
type(x)
print('o shape é:', x.shape)

x:
 [[1 2]
 [3 4]]
o shape é: (2, 2)


In [ ]:
np.zeros?

In [ ]:
#criação de np.zeros (contendo zeros) bidimensional
bidim = (2,2) # (linhas, colunas)
x = np.zeros(bidim)
print('x = \n', x)
print('o shape é:', x.shape)

x = 
 [[0. 0.]
 [0. 0.]]
o shape é: (2, 2)


In [ ]:
#criação de np.zeros (contendo zeros) bidimensional c/ 3 linhas
bidim2 = (3,2) # (linhas, colunas)
x = np.zeros(bidim2)
print('x = \n', x)
print('o shape é:', x.shape)

x = 
 [[0. 0.]
 [0. 0.]
 [0. 0.]]
o shape é: (3, 2)


In [ ]:
#criação de np.zeros (contendo zeros) bidimensional contendo apenas números 1
size = (1,1) # (linhas, colunas)
x = np.ones(size)
print('x = \n', x)
print('o shape é:', x.shape)

x = 
 [[1.]]
o shape é: (1, 1)


In [ ]:
#criação de np.zeros (contendo zeros) bidimensional contendo apenas números 1
size = (2,2) # (linhas, colunas)
x = np.ones(size)
print('x = \n', x)
print('o shape é:', x.shape)

x = 
 [[1. 1.]
 [1. 1.]]
o shape é: (2, 2)


In [ ]:
#criação de np.zeros (contendo zeros) bidimensional contendo apenas números 1
size = (10,10) # (linhas, colunas)
x = np.ones(size)
print('x = \n', x)
print('o shape é:', x.shape)

x = 
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
o shape é: (10, 10)


In [2]:
np.linspace?

In [3]:
np.eye?

In [ ]:
#criação de matriz identidade
n = 4
x = np.eye(n)
print('x é igual a: \n', x, '\n o shape é: ', x.shape)

x é igual a: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 
 o shape é:  (4, 4)


In [ ]:
help(np.random.seed)

Help on built-in function seed:

seed(...) method of numpy.random.mtrand.RandomState instance
    seed(self, seed=None)
    
    Reseed a legacy MT19937 BitGenerator
    
    Notes
    -----
    This is a convenience, legacy function.
    
    The best practice is to **not** reseed a BitGenerator, rather to
    recreate a new one. This method is here for legacy reasons.
    This example demonstrates best practice.
    
    >>> from numpy.random import MT19937
    >>> from numpy.random import RandomState, SeedSequence
    >>> rs = RandomState(MT19937(SeedSequence(123456789)))
    # Later, you want to restart the stream
    >>> rs = RandomState(MT19937(SeedSequence(987654321)))



In [ ]:
#criação de valores aleatórios

In [ ]:
#criação de valores dentro de um intervalo
#valores iniforme entre 5 e 15
x_min, x_max = 5, 15
x = np.linspace(start=x_min, stop=x_max, num=6)
print('x é igual a : ', x)
print('o shape é: ', x.shape)

x é igual a :  [ 5.  7.  9. 11. 13. 15.]
o shape é:  (6,)


In [ ]:
np.array([1,2,3] + np.array[1,2])

TypeError: ignored

In [ ]:
np.array([1,2,3]) + np.array([1,2,3])

array([2, 4, 6])

In [ ]:
#arrays com shape diferente resultará em erro.
np.array([1,2,3]) + np.array([1,2])

ValueError: ignored

In [ ]:
#array 3x3
a = np.array([1,2,3])
b = np.array([1,2,3])
print(a+b, 'shape de a: ', a.shape, 'shape de b: ', b.shape)

[2 4 6] shape de a:  (3,) shape de b:  (3,)


In [ ]:

#array 2x2
a = np.array([1,2])
b = np.array([1,2])
print(a+b, 'shape de a: ', a.shape, 'shape de b: ', b.shape)

[2 4] shape de a:  (2,) shape de b:  (2,)
